language: rust
sudo: required
os:
  - linux
  - osx
addons:
  postgresql: "9.4"
  apt:
    packages:
    - python-pip
    - libpq-dev
    - postgresql-server-dev-all
    - libclang1-3.4
    - libclang-3.4-dev
    - libclang-common-3.4-dev
    - clang-3.4
before_script: util/travis
script: make test
